### ISSUE TITLE
Front office user role (Assigned to)  is missing in task main view and task detail view

### ISSUE THREAD

**Issue by Tatuk** [digiexpress-io/digiexpress-parent#283]
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/c1d07ff6-f257-4c8c-a627-10348bee909e" />

**Comment by jocelynmutso** [comment]
Roles are not visible because, in the demo env, the security proxy does not provide any roles at the moment. If there are no roles that can be assigned, the entire role assignment is not visible. This is a feature.

**Comment by vahurkrouverk** [comment]
One issue was incorrect path for reading roles, now it is fixed and roles can be assigned to user.

**Comment by Tatuk** [comment]
@vahurkrouverk tested but still not working for me...Also as monitoring view don't show me the id's of dialog session I can't the roles creation directly from theWrench........which would help down to narrow the issue #305
